/**
 * TODO: define a license.
 */
package net.diogobohm.timed.impl.ui.taskitem;

import com.jgoodies.binding.adapter.Bindings;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import net.diogobohm.timed.api.ui.mvc.MVCView;
import net.diogobohm.timed.api.ui.mvc.model.formatter.TaskTimeFormatter;
import net.diogobohm.timed.impl.ui.taskitem.editmenu.TaskItemEditMenu;

/**
 *
 * @author diogo
 */
public class TaskItemPanel extends javax.swing.JPanel implements MVCView {

    private static final TaskTimeFormatter TIME_FORMATTER = new TaskTimeFormatter();

    private final TaskItemModel model;
    private final ActionListener editAction;
    private final ActionListener deleteAction;

    /**
     * Creates new form TaskItemPanel
     */
    public TaskItemPanel(TaskItemModel model, ActionListener editAction, ActionListener deleteAction) {
        this.model = model;
        this.editAction = editAction;
        this.deleteAction = deleteAction;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startTimeLabel = new javax.swing.JLabel();
        timeSplitLabel = new javax.swing.JLabel();
        stopTimeLabel = new javax.swing.JLabel();
        taskNameLabel = new javax.swing.JLabel();
        taskElapsedTimeLabel = new javax.swing.JLabel();

        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(442, 28));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        startTimeLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        startTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startTimeLabel.setText("StartTime");
        Bindings.bind(startTimeLabel, model.getStartDateHolder().getRenderer());

        timeSplitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeSplitLabel.setText(":");

        stopTimeLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        stopTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopTimeLabel.setText("StopTime");
        stopTimeLabel.setPreferredSize(new java.awt.Dimension(35, 16));
        Bindings.bind(stopTimeLabel, model.getStopDateHolder().getRenderer());

        taskNameLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        taskNameLabel.setText("TaskName");
        Bindings.bind(taskNameLabel, model.getTaskLabelHolder().getRenderer());

        taskElapsedTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        taskElapsedTimeLabel.setText("TaskTime");
        Bindings.bind(taskElapsedTimeLabel, model.getTaskElapsedTimeHolder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSplitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(taskNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskElapsedTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeLabel)
                    .addComponent(timeSplitLabel)
                    .addComponent(stopTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskNameLabel)
                    .addComponent(taskElapsedTimeLabel))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            TaskItemEditMenu menu = new TaskItemEditMenu(editAction, deleteAction);
            menu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JLabel stopTimeLabel;
    private javax.swing.JLabel taskElapsedTimeLabel;
    private javax.swing.JLabel taskNameLabel;
    private javax.swing.JLabel timeSplitLabel;
    // End of variables declaration//GEN-END:variables
}
