/**
 * TODO: define a license.
 */
package net.diogobohm.timed.impl.ui.tasklist;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import net.diogobohm.timed.impl.ui.taskitem.TaskItemController;

/**
 *
 * @author diogo.bohm
 */
public class TaskListPanel extends javax.swing.JPanel {

    private final TaskListModel model;

    public TaskListPanel() {
        this(null);
    }

    /**
     * Creates new form TaskListPanel2
     */
    public TaskListPanel(TaskListModel model) {
        this.model = model;

        initComponents();
        adjustLayout();

        if (model != null) {
            updateTaskItems();
            this.model.getTaskItemListHolder().addValueChangeListener(createTaskListChangeListener());
        }
    }

    private PropertyChangeListener createTaskListChangeListener() {
        return new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                updateTaskItems();
            }
        };

    }

    private void updateTaskItems() {
        removeAll();

        for (TaskItemController taskController : model.getTaskItemListHolder().getValue()) {
            add(taskController.getView());
        }

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void adjustLayout() {
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }
}
