/**
 * TODO: define a license.
 */
package net.diogobohm.timed.impl.ui.daytasklist;

import com.jgoodies.binding.adapter.Bindings;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import net.diogobohm.timed.impl.ui.tasklist.TaskListPanel;

/**
 *
 * @author diogo.bohm
 */
public class DayTaskListView extends javax.swing.JPanel {

    private final DayTaskListModel model;
    private final TaskListPanel taskListPanel;

    public DayTaskListView(DayTaskListModel model, TaskListPanel taskListPanel) {
        this.taskListPanel = taskListPanel;
        this.model = model;

        initComponents();
        this.model.getExpandHolder().addPropertyChangeListener(createExpandChangeListener());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        workedHoursLabel = new javax.swing.JLabel();
        dayNameLabel = new javax.swing.JLabel();
        toggleExpandLabel = new javax.swing.JLabel();
        taskListPanelContainer = new javax.swing.JPanel();

        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerPanelMouseClicked(evt);
            }
        });

        workedHoursLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        workedHoursLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        workedHoursLabel.setText("DayWorkedHours");
        Bindings.bind(workedHoursLabel, model.getDayWorkedTimeHolder());

        dayNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dayNameLabel.setText("Day name");
        Bindings.bind(dayNameLabel, model.getDateNameHolder());

        toggleExpandLabel.setText(">");
        Bindings.bind(toggleExpandLabel, model.getExpandLabelHolder());

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toggleExpandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workedHoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workedHoursLabel)
                    .addComponent(dayNameLabel)
                    .addComponent(toggleExpandLabel)))
        );

        taskListPanelContainer.setPreferredSize(new java.awt.Dimension(0, 0));
        taskListPanelContainer.setLayout(new java.awt.BorderLayout());

        taskListPanelContainer.add(taskListPanel);
        refreshTaskList();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taskListPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskListPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void headerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseClicked
        model.toggleExpand();
    }//GEN-LAST:event_headerPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayNameLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel taskListPanelContainer;
    private javax.swing.JLabel toggleExpandLabel;
    private javax.swing.JLabel workedHoursLabel;
    // End of variables declaration//GEN-END:variables

    private PropertyChangeListener createExpandChangeListener() {
        return new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                refreshTaskList();
            }
        };
    }

    private void refreshTaskList() {
        boolean expand = model.getExpandHolder().booleanValue();

        taskListPanelContainer.removeAll();
        taskListPanelContainer.setSize(0, 0);

        if (expand) {
            taskListPanelContainer.add(taskListPanel);
        }

        revalidate();
        repaint();
    }
}
