/**
 * TODO: define a license.
 */

package net.diogobohm.timed.ui;

import java.text.SimpleDateFormat;
import java.util.logging.SimpleFormatter;
import net.diogobohm.timed.domain.Task;
import net.diogobohm.timed.ui.formatter.TaskTimeFormatter;

/**
 *
 * @author diogo
 */
public class TaskItemPanel extends javax.swing.JPanel {

    private static final TaskTimeFormatter TIME_FORMATTER = new TaskTimeFormatter();

	/**
	 * Creates new form TaskItemPanel
	 */
	public TaskItemPanel() {
		initComponents();
    }

    public void setTask(Task task) {
        startTimeLabel.setText(TIME_FORMATTER.format(task.getStart()));
        stopTimeLabel.setText(TIME_FORMATTER.format(task.getFinish()));
    }

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startTimeLabel = new javax.swing.JLabel();
        timeSplitLabel = new javax.swing.JLabel();
        stopTimeLabel = new javax.swing.JLabel();
        taskNameLabel = new javax.swing.JLabel();
        tagListLabel = new javax.swing.JLabel();
        editTaskButton = new javax.swing.JButton();

        setOpaque(false);

        startTimeLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        startTimeLabel.setText("StartTime");

        timeSplitLabel.setText(":");

        stopTimeLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        stopTimeLabel.setText("StopTime");

        taskNameLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        taskNameLabel.setText("TaskName");

        tagListLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tagListLabel.setText("TagList");

        editTaskButton.setText("Edit");
        editTaskButton.setOpaque(false);
        editTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaskButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSplitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tagListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeLabel)
                    .addComponent(timeSplitLabel)
                    .addComponent(stopTimeLabel)
                    .addComponent(taskNameLabel)
                    .addComponent(tagListLabel)
                    .addComponent(editTaskButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTaskButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editTaskButton;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JLabel stopTimeLabel;
    private javax.swing.JLabel tagListLabel;
    private javax.swing.JLabel taskNameLabel;
    private javax.swing.JLabel timeSplitLabel;
    // End of variables declaration//GEN-END:variables
}
